services:
  db:
    image: mysql:8.0
    container_name: sales-analysis
    environment:
      MYSQL_DATABASE: MonitorVendas
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3300:3306"
    volumes:
      - D:\data\mysql\sales-analysis:/var/lib/mysql
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docs/changes.sql:/docker-entrypoint-initdb.d/02-changes.sql