spring.application.name=sales-analysis
spring.datasource.url=jdbc:mysql://localhost:3300/MonitorVendas
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
management.endpoints.web.cors.allowed-origins=${FRONTEND_URL}